In [1]:
import pandas as pd
import openpyxl

In [4]:
path = r"H:\Python\Etapa3\Aula4\CD2022_Populacao_2010_Compatibilizada_20231222.xlsx"

In [8]:
todas = pd.read_excel(path, sheet_name=None, header=None)
print(todas.keys())

dict_keys(['Municípios'])

In [9]:
bruto = pd.read_excel(path, sheet_name="Municípios", header=None)

In [10]:
bruto

,0,1,2,3,4,5,6,7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Censo Demográfico 2022: População e Domicílios...,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
3,NaN,RO,11,00015,Alta Floresta D'Oeste,24392,24392,21494
4,NaN,RO,11,00023,Ariquemes,90353,90353,96833
...,...,...,...,...,...,...,...,...
5572,NaN,DF,53,00108,Brasília,2570160,2572159,2817381
5573,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5574,NaN,Nota: Para o cálculo das taxas de crescimento ...,NaN,NaN,NaN,NaN,NaN,NaN
5575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5576,NaN,Fonte: IBGE. Diretoria de Pesquisas - DPE - C...,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
tabela_cortada = bruto.iloc[3:5573, 1:8].copy()

In [23]:
tabela_cortada = tabela_cortada.reset_index(drop=True)
tabela_cortada.columns = [
    "UF",
    "COD. UF",
    "COD. MUNIC",
    "NOME DO MUNICÍPIO",
    "População",
    "População 2010",
    "População Censo 2022",
]
for col in tabela_cortada.columns[4:6]:
    tabela_cortada[col] = pd.to_numeric(tabela_cortada[col], errors="coerce")
tabela_cortada

,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População,População 2010,População Censo 2022
0,RO,11,00015,Alta Floresta D'Oeste,24392,24392,21494
1,RO,11,00023,Ariquemes,90353,90353,96833
2,RO,11,00031,Cabixi,6313,6313,5351
3,RO,11,00049,Cacoal,78574,78574,86887
4,RO,11,00056,Cerejeiras,17029,17029,15890
...,...,...,...,...,...,...,...
5565,GO,52,22005,Vianópolis,12548,12548,14956
5566,GO,52,22054,Vicentinópolis,7371,7373,8768
5567,GO,52,22203,Vila Boa,4735,4735,4215
5568,GO,52,22302,Vila Propício,5145,5145,5815
5569,DF,53,00108,Brasília,2570160,2572159,2817381

In [26]:
tabela_cortada["Diferença"] = tabela_cortada["População Censo 2022"] - tabela_cortada["População 2010"]
tabela_cortada.sort_values("Diferença", ascending=False).reset_index(drop=True)

,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População,População 2010,População Censo 2022,Diferença
0,AM,13,02603,Manaus,1802014,1802014,2063689,261675
1,DF,53,00108,Brasília,2570160,2572159,2817381,245222
2,SP,35,50308,São Paulo,11253503,11253503,11451999,198496
3,SP,35,52205,Sorocaba,586625,586816,723682,136866
4,GO,52,08707,Goiânia,1302001,1301912,1437366,135454
...,...,...,...,...,...,...,...,...
5565,RS,43,14902,Porto Alegre,1409351,1409351,1332845,-76506
5566,PA,15,01402,Belém,1393399,1393399,1303403,-89996
5567,RJ,33,04904,São Gonçalo,999728,999728,896744,-102984
5568,RJ,33,04557,Rio de Janeiro,6320446,6320446,6211223,-109223
5569,BA,29,27408,Salvador,2675656,2675656,2417678,-257978

In [35]:
tabela_cortada.to_csv(r"H:\Python\Etapa3\Aula4\Tabela4.csv")

In [33]:
pop_estado = (
    tabela_cortada.groupby(["COD. UF", "UF"], as_index=False)
      .agg(
          populacao_2010=("População 2010", "sum"),
          populacao_2022=("População Censo 2022", "sum"),
      )
)

pop_estado["Diferença"] = pop_estado["populacao_2022"] - pop_estado["populacao_2010"]

pop_estado.sort_values("Diferença", ascending=False).reset_index(drop=True)

    COD. UF  UF  populacao_2010 populacao_2022 Diferença
0        35  SP        41262199       44411238   3149039
1        42  SC         6248436        7610361   1361925
2        52  GO         6001789        7056495   1054706
3        41  PR        10444526       11444380    999854
4        31  MG        19597330       20539989    942659
5        51  MT         3035122        3658649    623527
6        15  PA         7581051        8120131    539080
7        13  AM         3483985        3941613    457628
8        23  CE         8451644        8794957    343313
9        32  ES         3514952        3833712    318760
10       50  MS         2449024        2757013    307989
11       26  PE         8796055        9058931    262876
12       53  DF         2572159        2817381    245222
13       25  PB         3766528        3974687    208159
14       21  MA         6574789        6776699    201910
15       43  RS        10693929       10882965    189036
16       14  RR          450479         636707    186228
17       22  PI         3119097        3271199    152102
18       28  SE         2067852        2210004    142152
19       24  RN         3168027        3302729    134702
20       17  TO         1383445        1511460    128015
21       29  BA        14017071       14141626    124555
22       12  AC          733559         830018     96459
23       33  RJ        15989929       16055174     65245
24       16  AP          669526         733759     64233
25       11  RO         1562409        1581196     18787
26       27  AL         3120887        3127683      6796

In [37]:
pop_estado.to_csv(r"H:\Python\Etapa3\Aula4\Tabela4_2.csv")